# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests

orbs:
  node: circleci/node@14.15.5

workflows:
  test_teaparty:
    jobs:
      - test
