version: 2.1
orbs:
  node: circleci/node@1.1.0
jobs:
  build:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install yarn
            - run: npx yarn install
      - run: npx yarn test
  run:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install yarn
            - run: npx yarn install
      - run: npx yarn test